@base_url = http://localhost:5000/api/phone-call/twilio

### Create a new outbound call
POST {{base_url}}/start-marketing-call
Content-Type: application/json

{
  "contacts": [
    {
      "phoneNumber": "+6285725868168",
      "instruction": "You are calling Friendly, the owner of Tolman Sdn Bhd, a construction company. Your tone should be relaxed when talking with this contact.",
      "greeting": "Hello, may I speak to Friendly, the owner of Tolman Sdn Bhd? This is Sarah calling from Meridian Properties"
    }
  ]
}